feat: added navbar
U-SWITCH/landing-page pull request #1
Opened 2024-10-17 12:59 UTC by KostLinux

2024-10-18 15:15 UTC, Matrix278 commented on validation_report.log
Ignore the file?

2024-10-18 17:33 UTC, Matrix278 commented
@KostLinux @Dan-I-El Checked locally, that's what I found that can be done better:
1. The U-Switch logo on navbar as a button that does unnecessary reload page, but I guess could be just the same as home navbar link (#cctv) - http://127.0.0.1:5500/#cctv

2. On Russian the link to AJAX is only within the AJAX word, but on Estonian it's within 2 words AJAX tooteid. Should be the same for both languages, as I think.
<img width="500" alt="image" src="https://github.com/user-attachments/assets/ce87b897-74c7-418a-9119-bacdad1c341d">
<img width="500" alt="image" src="https://github.com/user-attachments/assets/4a936c84-7fda-41d9-936d-87e2bfac218e">

3. On the navbar there is no active link coloring, like if I am on Teenused, I don't see other color on it, could be done also. Or maybe hover color at least if even needed.
<img width="500" alt="image" src="https://github.com/user-attachments/assets/05e0fbf8-bc28-4c3c-9bb4-f0e1c2898a34">

4. The footer of copyright should have configured 2024 to be updated next year -  © U SWITCH OÜ 2024 -> © U SWITCH OÜ 2024-2025
I have it done on my portfolio, you can check it out with JS script - https://github.com/Matrix278/portfolio/blob/master/index.html
https://github.com/Matrix278/portfolio/blob/master/js/main.js#L27C1-L29C1

5. Two images on the back, is it ok? Shouldn't it be just one image?
<img width="500" alt="image" src="https://github.com/user-attachments/assets/9f862452-817a-4530-9a5f-007ace1021ba">

6. Should the facebook and instagram making new tab with target="_blank" and not just redirect? Like it's done for the ajax page.

7. And was it ok for them to have the navbar like from the right start of the screen and to the left end of the screen? Not within the center how I remember they had it? That's about the container. 
<img width="500" alt="image" src="https://github.com/user-attachments/assets/30ba4e37-81ba-4522-869e-c8207b268c14">

2024-10-18 17:36 UTC, Matrix278 commented on assets/css/main.css
> +    text-align: center;
Duplicate of 'text-align: center;', delete.

2024-10-18 17:37 UTC, Matrix278 commented on assets/css/main.css
> +
Format the file, to remove unnecessary 2 newlines and fix tabs

2024-10-18 17:41 UTC, Matrix278 commented on assets/js/main.js
> +        var menu = document.getElementById('mobile-menu');
```suggestion
        let menu = document.getElementById('mobile-menu');
```

2024-10-18 17:41 UTC, Matrix278 commented on assets/js/main.js
> +            var menu = document.getElementById('mobile-menu');
```suggestion
            let menu = document.getElementById('mobile-menu');
```

2024-10-18 17:41 UTC, Matrix278 commented on assets/js/main.js
> +});
Format the js code also

2024-10-18 17:42 UTC, Matrix278 commented on translations/ee.json
> +}
I checked that the JSONs also could be formated better:
<img width="790" alt="image" src="https://github.com/user-attachments/assets/5718d85e-d910-4497-8724-f704060d1726">

2024-10-18 17:43 UTC, Matrix278 commented on translations/ru.json
> +    "services_header": "Мы предлагаем продукцию <a class='underline' href='https://ajax.systems/' target='_blank' title='https://ajax.systems/'>AJAX</a> с использованием современных устройств безопас
```suggestion
    "services_header": "Мы предлагаем продукцию <a class='underline' href='https://ajax.systems/' target='_blank' title='https://ajax.systems/'>AJAX</a> с использованием современных устройств безопасности и умных модулей",
```

2024-10-18 17:44 UTC, Matrix278 commented on translations/ee.json
> +    "about_paragraph_3": "                      - Denis Kitšigin ja Pavel Borovik (Juhatuse liikmed)",
What is happening with the big space within `about_paragraph_3` translation key?
    "about_paragraph_3": "                      - Denis Kitšigin ja Pavel Borovik (Juhatuse liikmed)",

2024-10-18 17:45 UTC, Matrix278 requested changes
Added comments

2024-10-19 06:11 UTC, KostLinux commented
@Matrix278 for them it was okay, that navbar will be from left to the right. But for the content (except the first cctv section) you can add the container to contribute.
Additionally could i ask on which view you see doubled pictures? `Two images on the back, is it ok? Shouldn't it be just one image?` 
Cause whenever i try to reproduce, i cannot find anything ;(

2024-10-19 10:19 UTC, Matrix278 approved these changes

2024-10-19 10:39 UTC, Dan-I-El commented
I don't even no how it should look so LGTM

2024-10-19 10:39 UTC, Dan-I-El approved these changes

2024-10-19 11:28 UTC, merged